spring:
  application:
    name: temporal-poc
  temporal:
    connection:
      target: localhost:7233
    namespace: default
    workers-auto-discovery:
      packages:
        - com.example.temporal_poc
